import DemoDocumentation from "../../../components/demo/DemoDocumentation";
import DemoHeader from "../../../components/demo/DemoHeader";
import DemoSection from "../../../components/demo/DemoSection";
import "../../../components/demo/demo.css";
import "./navigation-demo.css";
const sizes = ["xs", "sm", "md", "lg", "xl"] as const;
const variants = ["default", "bordered", "filled", "ghost"] as const;
const radii = ["none", "sm", "md", "lg", "full"] as const;
const states = ["default", "loading", "disabled"] as const;
import { useState } from "react";
import { Dropdown } from "shivanya-ui";
const placements=["bottom","bottomStart","bottomEnd","top","topStart","topEnd","left","right"] as const;
const docs={importCode:`import { Dropdown } from "shivanya-ui";`,usageCode:`<Dropdown><Dropdown.Trigger>Actions</Dropdown.Trigger><Dropdown.Content><Dropdown.Item>Edit</Dropdown.Item><Dropdown.Item>Delete</Dropdown.Item></Dropdown.Content></Dropdown>`,props:[{name:"size",type:"xs | sm | md | lg | xl",default:"md"},{name:"variant",type:"default | bordered | filled | ghost",default:"default"},{name:"radius",type:"none | sm | md | lg | full",default:"md"},{name:"placement",type:"bottom | bottomStart | bottomEnd | top | topStart | topEnd | left | right",default:"bottomStart"},{name:"defaultOpen",type:"boolean",default:"false"},{name:"open",type:"boolean",default:"undefined"},{name:"onOpenChange",type:"(open: boolean) => void",default:"undefined"}]};
function DemoDropdown(props:any){return <Dropdown {...props}><Dropdown.Trigger>Open menu</Dropdown.Trigger><Dropdown.Content><Dropdown.Item icon="✓">Edit</Dropdown.Item><Dropdown.Item active>Duplicate</Dropdown.Item><Dropdown.Item disabled>Disabled</Dropdown.Item><Dropdown.Item rightSection="⌘K">Keyboard</Dropdown.Item></Dropdown.Content></Dropdown>}
export default function DropdownDemo(){const [open,setOpen]=useState(false);return <section className="demo"><DemoHeader title="Dropdown" description="Displays contextual actions from a trigger."/><DemoSection title="Basic"><DemoDropdown/></DemoSection><DemoSection title="Sizes"><div className="navigation-demo-grid navigation-demo-grid-5">{sizes.map(size=><div className="navigation-demo-card navigation-demo-overflow" key={size}><span className="navigation-demo-label">{size.toUpperCase()}</span><DemoDropdown size={size}/></div>)}</div></DemoSection><DemoSection title="Variants"><div className="navigation-demo-grid navigation-demo-grid-4">{variants.map(variant=><div className="navigation-demo-card navigation-demo-overflow" key={variant}><span className="navigation-demo-label">{variant}</span><DemoDropdown variant={variant}/></div>)}</div></DemoSection><DemoSection title="Radius"><div className="navigation-demo-grid navigation-demo-grid-5">{radii.map(radius=><div className="navigation-demo-card navigation-demo-overflow" key={radius}><span className="navigation-demo-label">{radius}</span><DemoDropdown radius={radius}/></div>)}</div></DemoSection><DemoSection title="Placements"><div className="navigation-demo-grid navigation-demo-grid-4">{placements.map(placement=><div className="navigation-demo-card navigation-demo-overflow" key={placement}><span className="navigation-demo-label">{placement}</span><DemoDropdown placement={placement}/></div>)}</div></DemoSection><DemoSection title="States"><div className="navigation-demo-grid navigation-demo-grid-3">{states.map(state=><div className="navigation-demo-card" key={state}><span className="navigation-demo-label">{state}</span><DemoDropdown state={state}/></div>)}</div></DemoSection><DemoSection title="Controlled"><Dropdown open={open} onOpenChange={setOpen}><Dropdown.Trigger>{open?"Close":"Open"}</Dropdown.Trigger><Dropdown.Content><Dropdown.Item onClick={()=>setOpen(false)}>Controlled action</Dropdown.Item></Dropdown.Content></Dropdown><span className="navigation-demo-note">Open: {String(open)}</span></DemoSection><DemoDocumentation importCode={docs.importCode} usageCode={docs.usageCode} props={docs.props}/></section>}
