import DemoDocumentation from "../../../components/demo/DemoDocumentation";
import DemoHeader from "../../../components/demo/DemoHeader";
import DemoSection from "../../../components/demo/DemoSection";
import "../../../components/demo/demo.css";
import "./navigation-demo.css";
const sizes = ["xs", "sm", "md", "lg", "xl"] as const;
const variants = ["default", "bordered", "filled", "ghost"] as const;
const radii = ["none", "sm", "md", "lg", "full"] as const;
const states = ["default", "loading", "disabled"] as const;
import { useState } from "react"; import { Pagination } from "shivanya-ui";
const docs={importCode:`import { Pagination } from "shivanya-ui";`,usageCode:`<Pagination total={20} defaultPage={1} onChange={page => console.log(page)} />`,props:[{name:"size",type:"xs | sm | md | lg | xl",default:"md"},{name:"variant",type:"default | bordered | filled | ghost",default:"default"},{name:"radius",type:"none | sm | md | lg | full",default:"md"},{name:"total",type:"number",default:"undefined"},{name:"page",type:"number",default:"undefined"},{name:"defaultPage",type:"number",default:"1"},{name:"siblingCount",type:"number",default:"1"},{name:"boundaryCount",type:"number",default:"1"}]};
export default function PaginationDemo(){const [page,setPage]=useState(1);return <section className="demo"><DemoHeader title="Pagination" description="Provides controls for navigating between pages of content."/><DemoSection title="Basic"><Pagination total={10}/></DemoSection><DemoSection title="Sizes"><div className="navigation-demo-grid navigation-demo-grid-5">{sizes.map(size=><div className="navigation-demo-card" key={size}><span className="navigation-demo-label">{size.toUpperCase()}</span><Pagination size={size} total={10}/></div>)}</div></DemoSection><DemoSection title="Variants"><div className="navigation-demo-grid navigation-demo-grid-4">{variants.map(variant=><div className="navigation-demo-card" key={variant}><span className="navigation-demo-label">{variant}</span><Pagination variant={variant} total={10}/></div>)}</div></DemoSection><DemoSection title="Radius"><div className="navigation-demo-grid navigation-demo-grid-5">{radii.map(radius=><div className="navigation-demo-card" key={radius}><span className="navigation-demo-label">{radius}</span><Pagination radius={radius} total={10}/></div>)}</div></DemoSection><DemoSection title="States"><div className="navigation-demo-grid navigation-demo-grid-3">{states.map(state=><div className="navigation-demo-card" key={state}><span className="navigation-demo-label">{state}</span><Pagination state={state} total={10}/></div>)}</div></DemoSection><DemoSection title="Interactive"><Pagination total={20} page={page} onChange={setPage}/><span className="navigation-demo-note">Current page: {page}</span></DemoSection><DemoSection title="Custom Items"><Pagination><Pagination.Item>«</Pagination.Item><Pagination.Item>‹</Pagination.Item><Pagination.Item active>1</Pagination.Item><Pagination.Item>2</Pagination.Item><Pagination.Item>3</Pagination.Item><Pagination.Item>›</Pagination.Item></Pagination></DemoSection><DemoDocumentation importCode={docs.importCode} usageCode={docs.usageCode} props={docs.props}/></section>}
