import DemoDocumentation from "../../../components/demo/DemoDocumentation";
import DemoHeader from "../../../components/demo/DemoHeader";
import DemoSection from "../../../components/demo/DemoSection";
import "../../../components/demo/demo.css";
import "../shell-demo.css";
import { AppShell, useBreakpoint, useIsMobile, useLayout, useSidebar } from "shivanya-shell";
import { DemoButton } from "../_demo-utils";

function HookState(){const shell=useSidebar();const layout=useLayout();const mobile=useIsMobile();const desktop=useBreakpoint("(min-width: 768px)");return <div className="shell-demo-stack"><div className="shell-demo-grid"><div className="shell-demo-card"><strong>useSidebar</strong><p className="shell-demo-muted">open: {String(shell.sidebarOpen)}</p><p className="shell-demo-muted">collapsed: {String(shell.sidebarCollapsed)}</p></div><div className="shell-demo-card"><strong>useLayout</strong><p className="shell-demo-muted">mobileOpen: {String(layout.mobileOpen)}</p></div><div className="shell-demo-card"><strong>useBreakpoint</strong><p className="shell-demo-muted">mobile: {String(mobile)}</p><p className="shell-demo-muted">desktop: {String(desktop)}</p></div></div><div className="shell-demo-row"><DemoButton onClick={shell.toggleSidebar}>Toggle sidebar</DemoButton><DemoButton onClick={shell.toggleSidebarCollapsed}>Toggle collapsed</DemoButton></div></div>}
export default function ShellHooksDemo(){return <section className="demo"><DemoHeader title="Shell Hooks" description="Reusable hooks for shared shell state and responsive breakpoint detection." /><DemoSection title="Interactive"><AppShell><HookState/></AppShell></DemoSection><DemoSection title="Hooks"><div className="shell-demo-grid"><div className="shell-demo-card"><strong>useShell</strong><p className="shell-demo-muted">Full shell context API.</p></div><div className="shell-demo-card"><strong>useSidebar</strong><p className="shell-demo-muted">Sidebar-focused state helpers.</p></div><div className="shell-demo-card"><strong>useLayout</strong><p className="shell-demo-muted">Compatibility alias for shell layout state.</p></div><div className="shell-demo-card"><strong>useBreakpoint</strong><p className="shell-demo-muted">Media-query driven responsive state.</p></div></div></DemoSection><DemoDocumentation importCode={'import { useShell, useSidebar, useLayout, useBreakpoint } from "shivanya-shell";'} usageCode={'const { sidebarOpen, toggleSidebar } = useSidebar();'} /></section>}
